services:
  app:
    image: ghcr.io/richmondnda/laravel_example-api:latest
    container_name: laravel-api
    restart: unless-stopped
    ports:
      - "8080:80"
    environment:
      APP_NAME: "Laravel API"
      APP_ENV: production
      APP_KEY: base64:sZ29iOiPlmDGPK9s2031K2qo94SqnXKRIX2bdV/A/RI=
      APP_DEBUG: "false"
      APP_URL: http://localhost:8080
      
      # Database MySQL
      DB_CONNECTION: mysql
      DB_HOST: mysql
      DB_PORT: 3306
      DB_DATABASE: laravel
      DB_USERNAME: laravel
      DB_PASSWORD: secret
      
      # Cache & Session
      CACHE_DRIVER: redis
      SESSION_DRIVER: redis
      QUEUE_CONNECTION: redis
      REDIS_HOST: redis
      REDIS_PASSWORD: null
      REDIS_PORT: 6379
    volumes:
      - ./storage:/var/www/html/storage
    depends_on:
      mysql:
        condition: service_healthy
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - laravel-network

  mysql:
    image: mysql:8.4
    container_name: laravel-mysql
    restart: unless-stopped
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: laravel
      MYSQL_USER: laravel
      MYSQL_PASSWORD: secret
    volumes:
      - mysql-data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-proot"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - laravel-network

  postgres:
    image: postgres:16-alpine
    container_name: laravel-postgres
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: laravel
      POSTGRES_USER: laravel
      POSTGRES_PASSWORD: secret
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U laravel"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - laravel-network

  redis:
    image: redis:alpine
    container_name: laravel-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - laravel-network

volumes:
  mysql-data:
    driver: local
  postgres-data:
    driver: local
  redis-data:
    driver: local

networks:
  laravel-network:
    driver: bridge
